#! /usr/bin/env ruby

def run_in_order(commands)
  commands.each do |command|
    abort "Failed to install - '#{command}' failed" unless system(command)
  end
end

puts 'Installing blind ...'
puts 'Please enter your password to allow this installation.'
run_in_order [
  'sudo cp ./bin/blind /usr/local/bin/blind',
  'sudo mkdir /usr/local/lib/blind',
  'sudo cp -r ./src/ /usr/local/lib/blind',
  'sudo cp ./README.md /usr/local/lib/blind'
]

puts '... installed successfully. Try it out with "blind --help".'
